# Generated by Django 2.1.5 on 2019-01-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20190131_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdetails',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='postcode',
            field=models.IntegerField(default='1111'),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(default='state', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='street_name',
            field=models.CharField(default='Baker Street 221', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='suburb',
            field=models.CharField(default='England', max_length=150),
        ),
        migrations.DeleteModel(
            name='AddressDetails',
        ),
    ]
