# Generated by Django 2.1.5 on 2019-02-01 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20190131_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='postcode',
            field=models.IntegerField(blank=True, default='1111'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, default='state', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='street_name',
            field=models.CharField(blank=True, default='Baker Street 221', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='suburb',
            field=models.CharField(blank=True, default='England', max_length=150),
        ),
    ]
